version: '3.8'

services:
  nginx-local:
    image: nginx:latest
    container_name: nginx-local-dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf
      - ./certs/localhost+2.pem:/etc/nginx/certs/localhost+2.pem
      - ./certs/localhost+2-key.pem:/etc/nginx/certs/localhost+2-key.pem
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
