version: '3.8'

services:
  nginx-local:
    image: nginx:latest
    container_name: nginx-local-dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/local.conf:/etc/nginx/conf.d/local.conf:ro
      - ./certs/localhost+2.pem:/etc/nginx/certs/localhost+2.pem
      - ./certs/localhost+2-key.pem:/etc/nginx/certs/localhost+2-key.pem
      # Remove default config
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy

networks:
  proxy:
    name: nginx-proxy
    external: true