version: '2'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:dev
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    volumes:
      - ./my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    networks:
      - proxy
    volumes:
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:

networks:
  proxy:
    external:
      name: nginx-proxy
