# Define maximum file upload size
client_max_body_size 100m;

# Direct 503 errors to custom page
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        error_page 503 /503/index.html;
        location = /503/index.html {
                root /usr/share/nginx/html;
                internal;
        }
        location / {
                return 503;
        }
}