#!/bin/bash

# Last update: 2021-04-15
# Creates all environment variables necessary to manage the site's servers
# If you wish to rewrite old variables, you must remove them from the environment file yourself
# For general info about enviroment variables, see this article:
# https://medium.com/chingu/an-introduction-to-environment-variables-and-how-to-use-them-f602f66d15fa

ENV_PATH="/etc/environment"

# Prevents an environment variable from being added multiple times
addIfNeeded() {
        grep -qxF "$1" $ENV_PATH || echo "$1" >> $ENV_PATH
}

# Helper method for prompting environment variables
prompt() {
    read -p "Enter $1: " VALUE
    addIfNeeded "$1=\"$VALUE\""
}

# 1) Project variables
echo "PACKAGE_ROOT is used to start the project."
echo "Examples: ~, ~/Documents/Web\ Projects"
prompt "PACKAGE_ROOT"
echo "PACKAGE_URL is used to download the project's source code."
echo "Example: https://github.com/MattHalloran/NLN.git"
prompt "PACKAGE_URL"
echo "PACKAGE_NAME should match the repository name"
echo "Example: NLN"
prompt "PACKAGE_NAME"
# 1) Flask variables
echo "FLASK_APP allows Flask to locate the Python file containing route endpoints."
echo "This must match the path supplied in the backend's config.py file."
prompt "FLASK_APP"
# 2) Database variables
echo "DB_PASSWORD is required for connecting to the PostgreSQL database."
echo "This can be anything, but it is recommended to use a password generator."
prompt "DB_PASSWORD"
echo "DB_USER is also required for connecting to the PostgreSQL database."
echo "This must match the name supplied in the backend's config.py file."
prompt "DB_USER"
# 2) User authentication variables
echo "NLN_SIGN_KEY is required for authenticating user's session tokens, which allows users to stay logged in for a certain period of time."
echo "This can be anything, but is is recommended to use a password generator."
prompt "NLN_SIGN_KEY"
# 3) Twilio variables
echo "Twilio is a cloud communications service."
echo "It is a great tool for sending text messages to users."
echo "If you do not want to set up Twilio, you can leave the following Twilio variables blank."
echo "TWILIO_ACCOUNT_SID is an account identifier generated by Twilio. It can be found at twilio.com/console"
prompt "TWILIO_ACCOUNT_SID"
echo addIfNeeded "TWILIO_AUTH_TOKEN is an API key generated by Twilio, which can also be found at twilio.com/console"
prompt "TWILIO_AUTH_TOKEN"
# 4) Email variables
prompt "AFA_EMAIL_USERNAME"
prompt "AFA_EMAIL_FROM"
prompt "AFA_EMAIL_PASSWORD"

echo "All environment variables have been set. These will not go into effect until you log out and in"