#!/bin/bash

# Last update: 2021-04-15
# Creates all environment variables necessary to manage the site's servers
# For general info about enviroment variables, see this article:
# https://medium.com/chingu/an-introduction-to-environment-variables-and-how-to-use-them-f602f66d15fa
# Flags:
#   -r Remove aliases instead of setting

HERE=`dirname $0`
source "$HERE/formatting.sh"

COMPONENT="Environment variables"
REMOVE=false
FILE_PATH="/etc/environment"

while getopts ":r" opt; do
    case ${opt} in
        r )
            REMOVE=true
        ;;
        \? ) 
            echo "Handles $COMPONENT setup"
            echo "Usage: cmd [-u]"
            exit 1
        ;;
    esac
done

declare -a vars=("WEBSITE_NAME" 
                "PACKAGE_ROOT"
                "PACKAGE_URL"
                "PACKAGE_NAME"
                "FLASK_APP"
                "DB_PASSWORD"
                "DB_USER"
                "NLN_SIGN_KEY"
                "TWILIO_ACCOUNT_SID"
                "TWILIO_AUTH_TOKEN"
                "AFA_EMAIL_USERNAME"
                "AFA_EMAIL_FROM"
                "AFA_EMAIL_PASSWORD"
                )

# Removes all instances of an environment variable
# Params:
#   1) The variable name
removeVar() {
    # Remove existing matching lines
    grep -vwE "^$1=" $FILE_PATH > $FILE_PATH
}

# Sets an environment variable. If variable already exists,
# it is replaced with the new value
# Params:
#   1) The variable name
#   2) The variable value
setVar() {
    removeVar $1
    # Add new line
    echo "$1=\"$2\"" >> $ENV_PATH
}

# Helper method for prompting environment variables
prompt() {
    read -p "Enter $1: " VALUE
    setVar $1 $VALUE
}

add() {
    group "Setting $COMPONENT"

    info "${var[0]} is the website's url, EXCEPT for the www."
    info "Example: newlifenurseryinc.com"
    prompt ${var[0]}

    info "${var[1]} is used to start the project."
    info "Examples: ~, ~/Documents/Web\ Projects"
    prompt ${var[1]}

    info "${var[2]} is used to download the project's source code."
    info "Example: https://github.com/MattHalloran/NLN.git"
    prompt ${var[2]}

    info "${var[3]} should match the repository name"
    info "Example: NLN"
    prompt ${var[3]}

    info "${var[4]} allows Flask to locate the Python file containing route endpoints."
    info "This must match the path supplied in the backend's config.py file."
    prompt ${var[4]}

    info "${var[5]} is required for connecting to the PostgreSQL database."
    info "This can be anything, but it is recommended to use a password generator."
    prompt ${var[5]}

    info "${var[6]} is also required for connecting to the PostgreSQL database."
    info "This must match the name supplied in the backend's config.py file."
    prompt ${var[6]}

    info "${var[7]} is required for authenticating user's session tokens, which allows users to stay logged in for a certain period of time."
    info "This can be anything, but is is recommended to use a password generator."
    prompt ${var[7]}

    info "Twilio is a cloud communications service."
    info "It is a great tool for sending text messages to users."
    info "If you do not want to set up Twilio, you can leave the following Twilio variables blank."
    info "${var[8]} is an account identifier generated by Twilio. It can be found at twilio.com/console"
    prompt ${var[8]}

    info addIfNeeded "${var[9]} is an API key generated by Twilio, which can also be found at twilio.com/console"
    prompt ${var[9]}

    prompt ${var[10]}

    prompt ${var[11]}

    prompt ${var[12]}

    success "Set $COMPONENT. These will not go into effect until you log out and in"
}

remove() {
    group "Removing $COMPONENT"
    for i in "${var[@]}"
    do
        info "Removing $i"
        removeVar "$i"
    done
    success "Removed $COMPONENT"
}

if $REMOVE; then
    add
else
    remove
fi
